version: '2'

services:
  app:
    image: node
    command: tail -f /dev/null
    working_dir: /app
    ports:
      - 1337:1337
    volumes:
      - .:/app

  db:
    image: mongo

  mongo-admin:
    image: adicom/admin-mongo
    ports:
      - 1338:1234
